### ISSUE TITLE
Bug: Division by zero error on products #15

### ISSUE THREAD

**Issue by rjsdev2013** [NSS-Evening-Cohort-17/bangazon-llc-rjsdev2013#12]
CRITICAL ISSUE

When the client requests a single product, or all products, the status code is 500 and the response is always the following.

ZeroDivisionError at /products
division by zero
Dev Notes:

Create a new product so there's one without any reviews, that will trigger the error
The most recent feature added by the team was adding an average rating key to each product. You might want to start there and see if there are any try/except blocks you can implement.

**Comment by Alexey-ilin** [comment]
#25
